### PR TITLE
fix syscall nargs

### PR DESCRIPTION
**Pull request by kurorodev**

### CODE REVIEW

**Comment by anton2920** [comment]
How is this a fix? Now it doesn't even compile:

```
syscall/syscall.go:62:56: too many arguments in call to syscall.Syscall
        have (uintptr, uintptr, uintptr, uintptr, uintptr)
        want (uintptr, uintptr, uintptr, uintptr)
syscall/syscall.go:69:69: too many arguments in call to syscall.Syscall6
        have (uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr)
        want (uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr)
```

**Comment by kurorodev** [comment]
image
Using your package I got such logs, that's why I went to the source code of gofa

**Comment by anton2920** [comment]
What's your `GOOS`/`GOARCH`?

**Comment by kurorodev** [comment]
image
I have these one

**Comment by anton2920** [comment]
Now I see. This library is currently supported only on `freebsd`/`amd64`, so it's no wonder it doesn't work on Windows. Support for other operating systems will be added later, when I feel like doing it.

**Pull request closed without merging**
